### ISSUE TITLE
compiling with HSL

### ISSUE THREAD

**Issue by chkwon** [pjssilva/Algencan.jl#12]
How may I compile with HSL.  I've put `ma27d.f` in `sources/hsl/`. Is this enough? 

When I moved to `lib` folder and ran 
```
gcc -shared -o libalgencan.so -Wl,--whole-archive libalgencan.a -Wl,--no-whole-archive -lgfortran -L$PWD -lhsl
```
It says it cannot find `hsl`. Any help will be appreciated.

**Comment by pjssilva** [comment]
Unfortunately this question is outside of my scope. You should contact the authors of Algencan directly. It is more complicated that just putting a maXXX.f file somewhere, that is for sure. Anyhow I use this opportunity to try to push some changes to the Algencan people that should make the compilation with HSL easier.

**Comment by chkwon** [comment]
It will be awesome. Anyway, when I used Algencan with your package without HSL, it worked fine, although it couldn't solve some simple problems properly. Perhaps it is an issue without HSL, or just a limitation of Algencan.  Do you plan to make it a registered package?

**Comment by pjssilva** [comment]
Algencan without HSL may fail in badly conditioned problems since it does not use any linear system solver. I will wait one week to see if I can get a feedback from some of the Algencan authors (it is vacation period in Brazil). Maybe the best solution for me to distribute a patch I developed to allow for easier HSL compilation. It is just a "band-aid" but it might work well enough. I will let you know. And yes, my plan is to make a registered package. I have to update it to work with the new JuMP (with Julia 1.0).
